func test(x: Number) {

}

try {

  test ("hello");
} catch (e) {
  println ("Caught an error with message " + e.message);
  println (typeof (e));
}